modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Insane96/SemiHardcore/issues"
[[mods]]
modId="semihardcore"
version="${file.jarVersion}"
displayName="Semi-Hardcore"
displayURL="https://minecraft.curseforge.com/projects/semi-hardcore"
logoFile="examplemod.png"
# credits=""
authors="Insane96MCP"
description='''
Add lifes to the survival game.
'''
[[dependencies.semihardcore]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.semihardcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
